# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.TextField(default='Default title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=50),
            preserve_default=False,
        ),
    ]
