# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-29 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0004_auto_20180428_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('location_type', models.CharField(choices=[('Journey Point', 'Journey Point'), ('Trip Point', 'Trip Point')], default='Journey Point', max_length=50)),
                ('rating', models.CharField(default='2.5', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
