# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_locationpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='checkpoints',
        ),
        migrations.RemoveField(
            model_name='journeypoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='journeypoint',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='journeypoint',
            name='longitude',
        ),
        migrations.AddField(
            model_name='journey',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journey',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journeypoint',
            name='journey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.Journey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journeypoint',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='info.LocationPoint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journeypoint',
            name='point_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journeypoint',
            name='tansport',
            field=models.CharField(choices=[('Bus', 'Bus'), ('AC1 Train', 'AC1 Train'), ('AC2 Train', 'AC2 Train')], default='BUS', max_length=100),
        ),
    ]
