# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-29 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20180429_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='cotravel_number',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
