# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-29 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_journey_cotravel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpoint',
            name='user',
        ),
    ]
