# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-29 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0008_remove_locationpoint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpoint',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
