# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-29 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_locationpoint_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeypoint',
            old_name='tansport',
            new_name='transport',
        ),
    ]
