# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20180429_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='resolved',
            field=models.CharField(default='No', max_length=50),
        ),
    ]
