# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-30 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20180430_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, default='photos/no_photo.jpg', upload_to='photos'),
        ),
    ]
