# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20180430_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, default='no_photo.jpg', upload_to='photos/'),
        ),
    ]
