# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-01 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20180430_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.TextField(),
        ),
    ]
