# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-01 09:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0017_auto_20180501_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('expected_budget', models.CharField(max_length=50)),
                ('cotravel_number', models.CharField(default='2', max_length=10)),
                ('trip_info', models.TextField()),
                ('posted', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('rating', models.CharField(default='2.5', max_length=10)),
                ('attractions', models.ManyToManyField(to='info.Attraction')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.LocationPoint')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='info.Trip')),
            ],
        ),
    ]
