# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-01 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_attraction_trip_trippoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='rating',
            field=models.CharField(default='3', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.CharField(default='4', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='expected_budget',
            field=models.CharField(default='5000', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='source',
            field=models.CharField(default='IIT Delhi', max_length=100),
        ),
    ]
