# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 03:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_auto_20180501_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 3, 4, 43, 293809, tzinfo=utc)),
        ),
    ]
