# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_userinfo_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_visit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
