# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_auto_20180502_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_visit',
            field=models.DateTimeField(),
        ),
    ]
