# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20180502_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='tavel_id',
            field=models.CharField(default='Going Home', max_length=50),
        ),
    ]
