# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20180502_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='travel_id',
            field=models.CharField(default='Going Home', max_length=50),
        ),
        migrations.AlterField(
            model_name='journeypoint',
            name='transport',
            field=models.CharField(choices=[('Bus', 'Bus'), ('AC1 Train', 'AC1 Train'), ('AC2 Train', 'AC2 Train'), ('Cab', 'Cab'), ('Sleeper Train', 'Sleeper Train')], default='BUS', max_length=100),
        ),
    ]
