# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 20:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0025_auto_20180502_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
